# **Bibliothèque Numpy > Numerical Python**

In [85]:
import numpy as np

In [86]:
revenus = [1800, 1500, 2200, 3000, 2172]

In [87]:
np.mean(revenus) # Moyenne

2134.4

In [88]:
revenus_array = np.array(revenus) # Création d'un tableau numpy

### *Création de tableaux spécifiques, couramment utilisés :*
#### np.zeros(n): 
Permet de créer un array **rempli de 0**, de n éléments ;
#### np.ones(n) : 
Similaire en tous points à la fonction présentée ci-dessus, à la différence que l’array sera **rempli cette fois-ci de 1** ;
#### np.arange(i, j, p)  : 
Permet de créer un array **rempli avec une séquence linéaire**, qui ira **de  i  à  j**, par pas de  p  ;
#### np.linspace(i, j, n) : 
Permet de créer un array de  **n  valeurs espacées uniformément** entre  i  et  j.

In [89]:
revenus_array.dtype # Retourne le type des données d'un array_numpy

dtype('int32')

In [90]:
revenus_array = revenus_array.astype(float) # Converti le type de donnée

In [91]:
print(revenus_array)

[1800. 1500. 2200. 3000. 2172.]


In [92]:
revenus_array.dtype

dtype('float64')

In [106]:
revenus_array = np.int8(revenus_array)

In [107]:
revenus_array.dtype

dtype('int8')

In [108]:
revenus_array

array([   8,  -36, -104,  -72,  124], dtype=int8)

In [113]:
revenus_array = np.single

In [99]:
revenus_array

dtype('int32')

In [118]:
revenus_array = np.array(revenus)

In [119]:
revenus_array.dtype

dtype('int32')

In [120]:
revenus_array

array([1800, 1500, 2200, 3000, 2172])

In [121]:
revenus_array = revenus_array.astype(float)

In [122]:
revenus_array.dtype

dtype('float64')

In [123]:
revenus_array

array([1800., 1500., 2200., 3000., 2172.])

### Accédez à plusieurs éléments contigus :

#### nom_array[i:j:p] , avec :
         i  : l’indice du début ;
         j  : l’indice de fin ;
         p : le pas.

In [124]:
revenus_array[2:4]

array([2200., 3000.])

In [125]:
revenus_array[:2]

array([1800., 1500.])

In [126]:
revenus_array[:len(revenus_array):2]

array([1800., 2200., 2172.])

In [130]:
revenus_array[::-1]                        # Inversion Liste

array([2172., 3000., 2200., 1500., 1800.])

In [131]:
revenus_array[revenus_array > 2000]        # Accès conditionnel

array([2200., 3000., 2172.])

In [132]:
revenus_array

array([1800., 1500., 2200., 3000., 2172.])

In [133]:
revenus_array[(revenus_array > 2000) & (revenus_array < 3000)]

array([2200., 2172.])

revenus_array[revenus_array > 2000] = 0 , remplace **tous les éléments supérieurs à 2 000** au sein de notre array **par 0**

In [134]:
revenus_array.shape

(5,)

In [144]:
# calculer la moyenne
revenus_array.mean()

2134.4

In [149]:
# Calculer un arrondi (ici à une virgule)
arrondi = round(revenus_array.mean(),1)
print(arrondi)

2134.4


In [135]:
# calculer le maximum (ou le minimum) :
revenus_array.max()
revenus_array.min()

1500.0

In [137]:
# accéder à l’indice de l’élement minimum (ou maximum) :
revenus_array.argmin()
revenus_array.argmax()

3

In [138]:
revenus_array

array([1800., 1500., 2200., 3000., 2172.])

In [139]:
# ordonner par ordre croissant :
revenus_array.sort()
print(revenus_array)

[1500. 1800. 2172. 2200. 3000.]


In [140]:
# calculer la somme :
revenus_array.sum()

10672.0

### Tableaux Multidimensionnels:
tab1 = np.array([[1, 2],
    [3, 4],
        [5, 6]]) > 3 lignes et 2 colonnes

tab2 = np.array([[1, 2, 3],
        [4, 5, 6]]) > 2 lignes et 3 colonnes

In [150]:
# un tableau de 3x5 rempli de 1
np.ones((3, 5))
# un tableau de 4 lignes et de 4 colonnes contenant que des 0
np.zeros((4, 4))
# un tableau de 6x3 rempli de valeurs aléatoires comprises entre 0 et 1
np.random.random((6, 3))
# un tableau de 3x3 rempli de valeurs aléatoires entières, comprises entre 1 et 10
np.random.randint(1, 10, size=(3, 3))

array([[7, 5, 5],
       [1, 1, 8],
       [6, 5, 2]])

In [160]:
# Calcul matriciel :
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 10], [15, 20]])
C = np.array([[2, 4, 6], [8, 10, 12]])
print("A = ",A)
print("B = ",B)
print("A + B = ",(A + B))

A =  [[1 2]
 [3 4]]
B =  [[ 5 10]
 [15 20]]
A + B =  [[ 6 12]
 [18 24]]


# Transformez vos données en tableaux

Nous avons cette fois 10 clients avec trois informations à disposition sur chacun d’eux :
- le revenu mensuel
- l'âge du client
- le nombre d’enfants à charge

L’objectif va être de créer un tableau NumPy à partir de ces informations et de répondre aux différentes demandes formulées par notre service prêt en manipulant ce tableau avec les différentes techniques présentées tout au long de ce chapitre.

In [161]:
import numpy as np

In [162]:
hugo = [1800, 21, 0]
richard = [1500, 54, 2]
emilie = [2200, 28, 3]
pierre = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
yohann = [1400, 23, 0]
anne = [1200, 25, 1]
thibault = [1100, 19, 0]
emmanuel = [1300, 31, 2]

tableau = [hugo, richard, emilie, pierre, paul, deborah,
           yohann, anne, thibault, emmanuel]

display(tableau)

[[1800, 21, 0],
 [1500, 54, 2],
 [2200, 28, 3],
 [3000, 37, 1],
 [2172, 37, 2],
 [5000, 32, 0],
 [1400, 23, 0],
 [1200, 25, 1],
 [1100, 19, 0],
 [1300, 31, 2]]

In [164]:
data = np.array(tableau)

In [187]:
print(data[4])
print(data[4,:])
print(round(data[4,0]*0.35, 12))

[2172   37    2]
[2172   37    2]
760.2


In [172]:
louise = [1900, 31, 1]

In [174]:
np.vstack((data, louise))

array([[1800,   21,    0],
       [1500,   54,    2],
       [2200,   28,    3],
       [3000,   37,    1],
       [2172,   37,    2],
       [5000,   32,    0],
       [1400,   23,    0],
       [1200,   25,    1],
       [1100,   19,    0],
       [1300,   31,    2],
       [1900,   31,    1]])

In [176]:
revenus = data[:,0]
print(revenus)

[1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]


In [198]:
a = np.linspace(5, 10, 11)
print(a)
print(a[-3:-1])
print(a[-1])
print(a[1:-1])
print(a[0:len(a)])

[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]
[9.  9.5]
10.0
[5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]


In [189]:
a[a % 2 == 0]

array([ 6.,  8., 10.])

# **Panda**

#### Le data frame est un objet Python permettant de représenter les données sous forme de tableau, 
où chaque colonne est explicitement nommée. Il reprend les mêmes paradigmes que l’array NumPy :
chaque colonne peut naturellement être d’un type différent, mais une colonne ne peut contenir qu’un seul type !
Cette organisation simplifie l’accès aux variables, et permet de nombreuses manipulations de données plus ou moins complexes.

In [206]:
import pandas as pd

In [212]:
data_csv = pd.read_csv('clients.csv')      #Afin de faciliter l'import, placer les fichier dans le même dossier que le projet
data_csv
# data_csv.head()             Permet de lire les cinq premières lignes d'un tableau (Il est également possible de préciser entre parenthèses le nombre de lignes à afficher, max 60)
# data_csv.tail()             Permet de lire les cinq dernières lignes d'un tableau (Il est également possible de préciser entre parenthèses le nombre de lignes à afficher, max 60)

identifiant                            email                nom genre
0              0        LaurentDagenais@rhyta.com   Laurent Dagenais     M
1              1            GuyMarois@fleckens.hu         Guy Marois     M
2              2        BeaufortLesage@einrot.com    Beaufort Lesage     M
3              3        RussellDurand@armyspy.com     Russell Durand     M
4              4             AlexisRiel@rhyta.com        Alexis Riel     M
..           ...                              ...                ...   ...
223          223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F
224          224    ApollineMichaud@superrito.com   Apolline Michaud     F
225          225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F
226          226     FleurCaouette@jourrapide.com     Fleur Caouette     F
227          227      FrancisMasse@jourrapide.com      Francis Masse     M

[228 rows x 4 columns]

In [215]:
data_json = pd.read_json('clients.json')
data_json.head()

identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

In [216]:
data_excel = pd.read_excel('clients.xlsx')
data_excel.head()

identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

In [217]:
# afficher les 2 dernières lignes
display(data_excel.tail(2))

identifiant                         email             nom genre
226          226  FleurCaouette@jourrapide.com  Fleur Caouette     F
227          227   FrancisMasse@jourrapide.com   Francis Masse     M

In [219]:
# afficher les 5 premières et dernières lignes
display(data_excel)

identifiant                            email                nom genre
0              0        LaurentDagenais@rhyta.com   Laurent Dagenais     M
1              1            GuyMarois@fleckens.hu         Guy Marois     M
2              2        BeaufortLesage@einrot.com    Beaufort Lesage     M
3              3        RussellDurand@armyspy.com     Russell Durand     M
4              4             AlexisRiel@rhyta.com        Alexis Riel     M
..           ...                              ...                ...   ...
223          223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F
224          224    ApollineMichaud@superrito.com   Apolline Michaud     F
225          225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F
226          226     FleurCaouette@jourrapide.com     Fleur Caouette     F
227          227      FrancisMasse@jourrapide.com      Francis Masse     M

[228 rows x 4 columns]

In [221]:
dim = data_excel.shape
print(dim[0]) # 228 >> Nombre de ligne
print(dim[1]) # 4   >> Nombre de colonne

228
4


In [223]:
data_excel.dtypes

identifiant     int64
email          object
nom            object
genre          object
dtype: object

In [224]:
clients_array = data_excel.values
display(clients_array)

array([[0, 'LaurentDagenais@rhyta.com', 'Laurent Dagenais', 'M'],
       [1, 'GuyMarois@fleckens.hu', 'Guy Marois', 'M'],
       [2, 'BeaufortLesage@einrot.com', 'Beaufort Lesage', 'M'],
       [3, 'RussellDurand@armyspy.com', 'Russell Durand', 'M'],
       [4, 'AlexisRiel@rhyta.com', 'Alexis Riel', 'M'],
       [5, 'LeonLapresse@cuvox.de', 'Leon Lapresse', 'M'],
       [6, 'OrvilleRouthier@gustr.com', 'Orville Routhier', 'M'],
       [7, 'AgramantPepin@dayrep.com', 'Agramant Pepin', 'M'],
       [8, 'AiglentinaLambert@fleckens.hu', 'Aiglentina Lambert', 'F'],
       [9, 'TheodoreClavet@teleworm.us', 'Theodore Clavet', 'M'],
       [10, 'ByronLefebvre@jourrapide.com', 'Byron Lefebvre', 'M'],
       [11, 'FlorusDevoe@einrot.com', 'Florus Devoe', 'M'],
       [12, 'NormandArsenault@armyspy.com', 'Normand Arsenault', 'M'],
       [13, 'AcelineHughes@jourrapide.com', 'Aceline Hughes', 'F'],
       [14, 'GastonBrisette@superrito.com', 'Gaston Brisette', 'M'],
       [15, 'AgateGrandbois@gus