In [85]:
import numpy as np

In [86]:
revenus = [1800, 1500, 2200, 3000, 2172]

In [87]:
np.mean(revenus) # Moyenne

2134.4

In [88]:
revenus_array = np.array(revenus) # Création d'un tableau numpy

### *Création de tableaux spécifiques, couramment utilisés :*
#### np.zeros(n): 
Permet de créer un array **rempli de 0**, de n éléments ;
#### np.ones(n) : 
Similaire en tous points à la fonction présentée ci-dessus, à la différence que l’array sera **rempli cette fois-ci de 1** ;
#### np.arange(i, j, p)  : 
Permet de créer un array **rempli avec une séquence linéaire**, qui ira **de  i  à  j**, par pas de  p  ;
#### np.linspace(i, j, n) : 
Permet de créer un array de  **n  valeurs espacées uniformément** entre  i  et  j.

In [89]:
revenus_array.dtype # Retourne le type des données d'un array_numpy

dtype('int32')

In [90]:
revenus_array = revenus_array.astype(float) # Converti le type de donnée

In [91]:
print(revenus_array)

[1800. 1500. 2200. 3000. 2172.]


In [92]:
revenus_array.dtype

dtype('float64')

In [106]:
revenus_array = np.int8(revenus_array)

In [107]:
revenus_array.dtype

dtype('int8')

In [108]:
revenus_array

array([   8,  -36, -104,  -72,  124], dtype=int8)

In [113]:
revenus_array = np.single

In [99]:
revenus_array

dtype('int32')

In [118]:
revenus_array = np.array(revenus)

In [119]:
revenus_array.dtype

dtype('int32')

In [120]:
revenus_array

array([1800, 1500, 2200, 3000, 2172])

In [121]:
revenus_array = revenus_array.astype(float)

In [122]:
revenus_array.dtype

dtype('float64')

In [123]:
revenus_array

array([1800., 1500., 2200., 3000., 2172.])