# **Bibliothèque Numpy > Numerical Python**

In [85]:
import numpy as np

In [86]:
revenus = [1800, 1500, 2200, 3000, 2172]

In [87]:
np.mean(revenus) # Moyenne

2134.4

In [88]:
revenus_array = np.array(revenus) # Création d'un tableau numpy

### *Création de tableaux spécifiques, couramment utilisés :*
#### np.zeros(n): 
Permet de créer un array **rempli de 0**, de n éléments ;
#### np.ones(n) : 
Similaire en tous points à la fonction présentée ci-dessus, à la différence que l’array sera **rempli cette fois-ci de 1** ;
#### np.arange(i, j, p)  : 
Permet de créer un array **rempli avec une séquence linéaire**, qui ira **de  i  à  j**, par pas de  p  ;
#### np.linspace(i, j, n) : 
Permet de créer un array de  **n  valeurs espacées uniformément** entre  i  et  j.

In [89]:
revenus_array.dtype # Retourne le type des données d'un array_numpy

dtype('int32')

In [90]:
revenus_array = revenus_array.astype(float) # Converti le type de donnée

In [91]:
print(revenus_array)

[1800. 1500. 2200. 3000. 2172.]


In [92]:
revenus_array.dtype

dtype('float64')

In [106]:
revenus_array = np.int8(revenus_array)

In [107]:
revenus_array.dtype

dtype('int8')

In [108]:
revenus_array

array([   8,  -36, -104,  -72,  124], dtype=int8)

In [113]:
revenus_array = np.single

In [99]:
revenus_array

dtype('int32')

In [118]:
revenus_array = np.array(revenus)

In [119]:
revenus_array.dtype

dtype('int32')

In [120]:
revenus_array

array([1800, 1500, 2200, 3000, 2172])

In [121]:
revenus_array = revenus_array.astype(float)

In [122]:
revenus_array.dtype

dtype('float64')

In [123]:
revenus_array

array([1800., 1500., 2200., 3000., 2172.])

### Accédez à plusieurs éléments contigus :

#### nom_array[i:j:p] , avec :
         i  : l’indice du début ;
         j  : l’indice de fin ;
         p : le pas.

In [124]:
revenus_array[2:4]

array([2200., 3000.])

In [125]:
revenus_array[:2]

array([1800., 1500.])

In [126]:
revenus_array[:len(revenus_array):2]

array([1800., 2200., 2172.])

In [130]:
revenus_array[::-1]                        # Inversion Liste

array([2172., 3000., 2200., 1500., 1800.])

In [131]:
revenus_array[revenus_array > 2000]        # Accès conditionnel

array([2200., 3000., 2172.])

In [132]:
revenus_array

array([1800., 1500., 2200., 3000., 2172.])

In [133]:
revenus_array[(revenus_array > 2000) & (revenus_array < 3000)]

array([2200., 2172.])

revenus_array[revenus_array > 2000] = 0 , remplace **tous les éléments supérieurs à 2 000** au sein de notre array **par 0**

In [134]:
revenus_array.shape

(5,)

In [136]:
# calculer la moyenne
revenus_array.mean()

2134.4

In [135]:
# calculer le maximum (ou le minimum) :
revenus_array.max()
revenus_array.min()

1500.0

In [137]:
# accéder à l’indice de l’élement minimum (ou maximum) :
revenus_array.argmin()
revenus_array.argmax()

3

In [138]:
revenus_array

array([1800., 1500., 2200., 3000., 2172.])

In [139]:
# ordonner par ordre croissant :
revenus_array.sort()
print(revenus_array)

[1500. 1800. 2172. 2200. 3000.]


In [140]:
# calculer la somme :
revenus_array.sum()

10672.0